### PR TITLE
Follow django Python support map, add test for stable django 1.10 and…

### PR DESCRIPTION
**Pull request by hsmett**
… 1.11

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @hsmett 

Thanks for this.

The CI failed for Django 1.8 and Python 3.2. “Interpretor Not Found”

At this point I would be happy to just drop that. (Although if you’re happy to battle Travis, you are welcome)

**Comment by hsmett** [comment]
Hello @carltongibson, sorry it took me so long to answer!
I didn't noticed the Travis configuration file, I'm going to update it based on the official Django Python support:
https://docs.djangoproject.com/en/1.11/faq/install/
as I did for tox.
And maybe add Python 3.6 tests if it doesn't take me too much time :)

**Comment by hsmett** [comment]
Should be good :)

**Review by carltongibson — APPROVED** [review]
That’s lovely. Excellent job. Thank you!

**Comment by hsmett** [comment]
My pleasure! Do you plan to make a new release soon?

**Comment by carltongibson** [comment]
Not really. There hasn't been a code change since the last release. There's nothing to release...

**Pull request merged**
