### PR TITLE
Fix warning Django 1.9

### PR DESCRIPTION
**Pull request by SalahAdDin**
Fix the deprectaed warning for django.utils.importlib in Django 1.9

### CODE REVIEW

**Comment by carltongibson** [comment]
This isn't right. 

Django 1.8 doesn't support Python < 2.7 so `importlib.import_module` will always be available. 

Presumably this is meant to address #17 — but from the importation given there it's not clear that this is an AppConf issue. The file referenced is `python3.4/importlib/_bootstrap.py:321`. Can you provide a full traceback on #17 so we can see where the error is arising.

Additionally the tests are failing here.

**Comment by SalahAdDin** [comment]
I don't understand you, Django don't put any traceback, only put this warning, django.utils.importlib will be deprecated in django 1.8, so, i think that this app shouldbe remove this import.

**Comment by carltongibson** [comment]
> /home/tulipan/Proyectos/TiempoTurco/lib/python3.4/importlib/_bootstrap.py:321

This isn't an AppConf file. It's not even a Django file. So exactly how the warning is arising isn't at all clear. 

Maybe try opening the the debugger there and see what you can establish: 

       import pdb; pdb.set_trace()

**Comment by SalahAdDin** [comment]
Oh men, you see the warning? It's about django.utils.importlib, is very clear!

**Comment by carltongibson** [comment]
Yes, I see the warning. But: 

**1.** Warnings are formatted with a message as well as the file and line number where they arise. So whilst the message is coming from Django the warning is coming from `/home/tulipan/Proyectos/TiempoTurco/lib/python3.4/importlib/_bootstrap.py:321` — which is from  **Python** itself (yes?) and not from Django. 

**2.** `django.utils.importlib` is part of Django core — not AppConf — so if that's all you've got to go on, why do you think it's an AppConf problem and not a Django one? — Better to raise the issue on the Django Users mailing list I'd say. 

What is clear is that `django.utils.importlib` was deprecated (and will be removed) because from Python v2.7 the equivalent functionality is available as part of the standard library. Django 1.8 is only compatible with Python >=2.7, thus `importlib`will always be available. 

In the lines you identify for change in AppConf...

```
try:
    from importlib import import_module
except ImportError:
    from django.utils.importlib import import_module
```

... the `ImportError` will never be raised on any version of Python compatible with Django 1.8, thus the problematic `from django.utils.importlib...` will never be called.

This pattern — the `try... except...` is the standard way of handling backwards compatible import changes. This exact block will be common to **many** third-party apps in the Django ecosystem — it's not where this error is coming from. 

@jezdez Unless more information pinning this error to AppConf can be provided I'd say both this and the related #17 can be closed as non-issues.

**Comment by carltongibson** [comment]
Closing as per #17

**Pull request closed without merging**
