### PR TITLE
Add syntax highlighting

### PR DESCRIPTION
**Pull request by lcd1232**
Now README highlight python code

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
OK. Yep. Great. 👍

**Comment by carltongibson** [comment]
Except the travis build failed... I think we may need to update the Python versions. Fancy having a look?

**Comment by lcd1232** [comment]
@carltongibson I fixed travis build and broke up coverage.

**Comment by carltongibson** [comment]
@lcd1232 Brilliant. Let's have this then. Thanks for the input!

**Pull request merged**
