### PR TITLE
Measure code coverage with Codecov

### PR DESCRIPTION
**Pull request by treyhunner**
As [requested here][comment].

See django-compressor/django-compressor#659.

**Full disclosure**: I work for [Codecov][]

[comment]: https://github.com/django-compressor/django-appconf/pull/23#issuecomment-140683641
[codecov]: https://codecov.io

### CODE REVIEW

**Comment by treyhunner** [comment]
It looks like the tests are not actually running on Travis.  Travis is attempting to run `tox` for each build but seems to only run `flake8`.  [See here][travis].

[travis]: https://travis-ci.org/django-compressor/django-appconf/jobs/80650720#L112

**Comment by treyhunner** [comment]
Nevermind.  I accidentally clicked on a flake8 environment run.

The Codecov report seems to be uploading but is not being used for some reason.  @stevepeak do you know what might be going on [here][upload] (also see the "no coverage reports uploaded" above)?

[upload]: https://travis-ci.org/django-compressor/django-appconf/jobs/80650739#L203

**Comment by stevepeak** [comment]
@treyhunner the report looks like it made it [here](https://codecov.io/github/django-compressor/django-appconf?ref=00c89e6a1e5757ea79e69381eeadef117548ff86) Clicked on [this line](https://travis-ci.org/django-compressor/django-appconf/jobs/80650739#L226) in the build

**Comment by carltongibson** [comment]
Ok. Thanks guys. I'll merge this. If something isn't working I'll get back to you.

Great to have the help integrating CodeCov

**Pull request merged**
