### PR TITLE
use django.utils.six instead of standalone six

### PR DESCRIPTION
**Pull request by wtayyeb**
this app is working in django, so no need to add additional dependency when it exist. using django.utils.six is better.

### CODE REVIEW

**Comment by macro1** [comment]
I was looking for something unrelated and noticed the failing tests. The latest coverage.py version is incompatible with Python 3.2. You'll either need to drop Python 3.2 support, ignore the coverage errors, or require coverage be less than version 4, which introduced the breaking change.

See: https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using

**Comment by carltongibson** [comment]
Ah yes, it needs to be pinned to (I think) 3.1.7 — you can add that here if you wish.

**Comment by wtayyeb** [comment]
i dont know how to fix coverage problem with python 3.2, i have tried some but it seem not work!

**Comment by wtayyeb** [comment]
finally passes the ci checks! but it was not my problem! coverage 4 not supporting py3.2

**Comment by carltongibson** [comment]
Well done. Good persistence. 👍🏽

Thanks

**Pull request merged**
