### PR TITLE
Follow django Python support map, add tox/travis targets for stable django 2.0 and 2.1

### PR DESCRIPTION
**Pull request by joehybird**

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Yes. Good start. How about dropping unsupported versions and adding Python 3.7?

**Comment by joehybird** [comment]
I didn't want to break anything, but I can drop versions under 1.10 or 1.11.
Ok, I'll add python 3.7, good remark :)

**Comment by carltongibson** [comment]
Hey @joehybird Keep 1.11 for now. It's still LTS. But I think testing against 1.11-2.1 is enough. 

https://www.djangoproject.com/download/#supported-versions

**Comment by joehybird** [comment]
python 3.7 is not supported by travis, I must remove it.

**Comment by carltongibson** [comment]
No. Hold on. It is. ...

**Comment by joehybird** [comment]
I kept it in tox file.

**Comment by carltongibson** [comment]
c.f. https://github.com/encode/django-rest-framework/commit/9b7db8dd694dbaf451383890a2f79d571b97746e

**Comment by joehybird** [comment]
:+1: you saved my day (and some others)

**Review by carltongibson — APPROVED** [review]
OK. I think that looks good. Thanks for the effort @joehybird.

**Pull request merged**
