### PR TITLE
merge and update pypi!

### PR DESCRIPTION
**Pull request by wtayyeb**
Hi
its time to merge the develop brunch and update the pypi package
its a year from last update to pypi.

thanks

### CODE REVIEW

**Comment by carltongibson** [comment]
OK fine, I'll look at this. 

Just out of interest, why the need for the new release? All the changes seem internal...

**Comment by wtayyeb** [comment]
Ok it isn't a new release, just a patch fix!
Its up to you if you want or not to do it. I will appreciate anyway.

**Comment by carltongibson** [comment]
Hmmm. Well, nothing has changed — there's no reason to update — but I guess we should do a release at some point...

@jezdez @diox Can you add me (`carltongibson`) on PyPI? https://pypi.python.org/pypi/django-appconf/1.0.1

**Comment by diox** [comment]
@carltongibson : It seems that I don't have access to the package on PyPI

**Comment by wtayyeb** [comment]
Package Index Owner: jezdez
who is jezdez??

**Comment by jezdez** [comment]
@diox @carltongibson Added you as maintainers

**Comment by carltongibson** [comment]
OK. Thanks @jezdez!

I'll look at whether I can do anything immediately with the outstanding issues and do a release over the next few days.

**Comment by carltongibson** [comment]
https://github.com/django-compressor/django-appconf/releases/tag/v1.0.2

https://pypi.python.org/pypi/django-appconf/1.0.2

Enjoy.

**Pull request merged**
