### PR TITLE
Migrate from django.utils.six to six

### PR DESCRIPTION
**Pull request by aleksihakli**
Django #27753 has dropped six support

https://code.djangoproject.com/ticket/27753
https://github.com/django/django/commit/41384812efe209c8295a50d78b45e0ffb2992436

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Right... I guess it's time to think about version support then. 
(i.e. Shouldn't we just go Python 3 only, and bump the version number?)

**Comment by carltongibson** [comment]
Hey @diox @karyon — This has bearing on compressor too. For me, dropping Python 2 is timely/fine, but there should be some coordination I guess...

**Comment by diox** [comment]
I wouldn't drop Python 2 / Django 1.11 until both are EOL. We can drop Django < 1.11 though.

**Comment by aleksihakli** [comment]
We have dropped Python 2.x support in some places where the maintenance of Python 2.x code has made the code bases more difficult to develop. Here the support is already baked in and the project is very stable, though. IMO supporting Python 2.7 until the EOL is a nice thing to do unless it isn't a too big hassle. In this specific case it only requires adding the six dependency and changing one import.

Our other package depends on django-appconf and requires it for testing against Django master, but at this moment the tests fail due to the missing six dependency. 

Cutting a new release that supports upstream Django would be awesome.

Looking at the download (`30d`) stats, quite a few people still use Python 2.7 with django-appconf:

https://pypistats.org/packages/django-appconf

image

**Review by carltongibson — APPROVED** [review]
OK, all makes sense. Thanks both. 

Let's have this. I'll roll a new release (for Python 3.7 folks) this week.

**Pull request merged**
